### ISSUE TITLE
ERROR: post new roomtype

### ISSUE THREAD

**Issue by 1312629** [rocketspacer/roomsy-gateway#12]
JSON:  
```
{ 
   "capacity":{  
      "adults":"4",
      "children":"2"
   },
   "showOnWebsite":"false",
   "name":"TR",
   "acronym":"TR",
   "description":"TR",
   "propertyId":"5849933ab999de00110f2a98"
}
```
<img width="1275" alt="screen shot 2016-12-12 at 02 57 40" src="https://cloud.githubusercontent.com/assets/16290131/21083051/938464ac-c01a-11e6-94a1-4544b7be5369.png">

**Comment by rocketspacer** [comment]
Moved to roomsy-rooms (where it should be)
https://github.com/rocketspacer/roomsy-rooms/issues/4
